-- MySQL Script generated by MySQL Workbench
-- Sun Mar 21 14:05:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `isProfessor` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`, `email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Turma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `nomeTurma` VARCHAR(45) NOT NULL,
  `idProfessor` INT NOT NULL,
  UNIQUE INDEX `idTurma_UNIQUE` (`idTurma` ASC) VISIBLE,
  PRIMARY KEY (`idTurma`, `nomeTurma`, `idProfessor`),
  CONSTRAINT `fk_Turma_Usuario1`
    FOREIGN KEY (`idTurma`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AlunoMatriculado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AlunoMatriculado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AlunoMatriculado` (
  `idAluno` INT NOT NULL,
  `idTurma` INT NOT NULL,
  PRIMARY KEY (`idTurma`, `idAluno`),
  CONSTRAINT `fkAlunoMatriculadoTurma`
    FOREIGN KEY (`idTurma`)
    REFERENCES `mydb`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkAlunoMatriculadoUsuario`
    FOREIGN KEY (`idAluno`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conteudo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Conteudo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Conteudo` (
  `idConteudo` INT NOT NULL AUTO_INCREMENT,
  `idTurma` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `conteudo` VARCHAR(500) NULL,
  `dtPublicacao` DATE NULL,
  `isAtividade` BINARY NOT NULL DEFAULT 0,
  PRIMARY KEY (`idConteudo`),
  INDEX `fk_Conteudo_Turma_idx` (`idTurma` ASC) VISIBLE,
  CONSTRAINT `fk_Conteudo_Turma`
    FOREIGN KEY (`idTurma`)
    REFERENCES `mydb`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comentario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `idConteudo` INT NOT NULL,
  `comentario` VARCHAR(500) NOT NULL,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `dtComentario` DATE NOT NULL,
  INDEX `fk_Comentario_Conteudo_idx` (`idConteudo` ASC) VISIBLE,
  PRIMARY KEY (`comentario`, `nomeUsuario`),
  CONSTRAINT `fk_Comentario_Conteudo`
    FOREIGN KEY (`idConteudo`)
    REFERENCES `mydb`.`Conteudo` (`idConteudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Atividade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Atividade` (
  `idAtividade` INT NOT NULL,
  `idConteudo` INT NOT NULL,
  `notaAtividade` FLOAT NOT NULL,
  `dtMaxEntrega` DATE NULL,
  PRIMARY KEY (`idAtividade`, `idConteudo`),
  INDEX `fk_Atividade_Conteudo1_idx` (`idConteudo` ASC) VISIBLE,
  CONSTRAINT `fk_Atividade_Conteudo1`
    FOREIGN KEY (`idConteudo`)
    REFERENCES `mydb`.`Conteudo` (`idConteudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RespostaAtividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RespostaAtividade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RespostaAtividade` (
  `idAtividade` INT NOT NULL,
  `idAluno` INT NOT NULL,
  `repostaAtividade` BLOB NULL,
  `dtEntrega` DATE NOT NULL,
  `dtCorrecao` DATE NULL,
  `notaObtida` FLOAT NULL,
  INDEX `fk_Nota_AlunoMatriculado_idx` (`idAluno` ASC) VISIBLE,
  PRIMARY KEY (`idAtividade`, `idAluno`),
  CONSTRAINT `fk_Nota_Atividade`
    FOREIGN KEY (`idAtividade`)
    REFERENCES `mydb`.`Atividade` (`idAtividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota_AlunoMatriculado`
    FOREIGN KEY (`idAluno`)
    REFERENCES `mydb`.`AlunoMatriculado` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
